from openmandel.schema import PresetInfo

PRESETS: list[PresetInfo] = [
    PresetInfo(
        name="full_set",
        description="The iconic full Mandelbrot set silhouette.",
        center_real=-0.5,
        center_imag=0.0,
        recommended_zoom=1,
        recommended_max_iter=500,
        vibes=["classic", "iconic", "simple", "educational"],
        suggested_palettes=["classic", "magma", "monochrome"],
    ),
    PresetInfo(
        name="seahorse_valley",
        description="Classic deep-zoom spiral structures near Seahorse Valley.",
        center_real=-0.743643887037151,
        center_imag=0.13182590420533,
        recommended_zoom=100000,
        recommended_max_iter=1200,
        vibes=["spiral", "intricate", "cosmic", "cathedral", "deep zoom"],
        suggested_palettes=["electric_blue", "ice", "neon_purple"],
    ),
    PresetInfo(
        name="elephant_valley",
        description="Organic bulb-like and coral-like structures.",
        center_real=0.275,
        center_imag=0.0,
        recommended_zoom=80,
        recommended_max_iter=800,
        vibes=["organic", "coral", "rounded", "alien", "reef"],
        suggested_palettes=["rose_gold", "toxic_green", "magma"],
    ),
    PresetInfo(
        name="mini_mandelbrot",
        description="Nested Mandelbrot-like structures showing recursion.",
        center_real=-1.749,
        center_imag=0.0,
        recommended_zoom=12000,
        recommended_max_iter=1500,
        vibes=["nested", "recursive", "symbolic", "mirrored"],
        suggested_palettes=["gold_fire", "classic", "inferno"],
    ),
    PresetInfo(
        name="triple_spiral",
        description="Energetic spiral-heavy region with radial motion.",
        center_real=-0.088,
        center_imag=0.654,
        recommended_zoom=3000,
        recommended_max_iter=1200,
        vibes=["spiral", "galaxy", "radial", "energetic"],
        suggested_palettes=["electric_blue", "neon_purple", "gold_fire"],
    ),
    PresetInfo(
        name="antenna_tip",
        description="Sparse, stark details near the left antenna of the Mandelbrot set.",
        center_real=-1.999,
        center_imag=0.0,
        recommended_zoom=250,
        recommended_max_iter=1000,
        vibes=["minimal", "needle", "dark", "stark"],
        suggested_palettes=["monochrome", "ice", "classic"],
    ),
    PresetInfo(
        name="lightning_filaments",
        description="Thin high-contrast boundary filaments suitable for lightning-like renders.",
        center_real=-0.77568377,
        center_imag=0.13646737,
        recommended_zoom=60000,
        recommended_max_iter=1600,
        vibes=["lightning", "filament", "electric", "sharp", "storm"],
        suggested_palettes=["electric_blue", "ice", "toxic_green"],
    ),
    PresetInfo(
        name="spiral_galaxy",
        description="A rich spiral region suitable for galaxy-like compositions.",
        center_real=-0.761574,
        center_imag=-0.0847596,
        recommended_zoom=8000,
        recommended_max_iter=1200,
        vibes=["galaxy", "spiral", "nebula", "cosmic"],
        suggested_palettes=["neon_purple", "electric_blue", "magma"],
    ),
]

PRESET_MAP: dict[str, PresetInfo] = {p.name: p for p in PRESETS}
